version: '3.8'
services:
  jedivin-mysql:
    image: mysql:8.0.29
    volumes:
      - /tmp/volumes/jedivin-mysql/data
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=jedivindb
    command:            
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake      
    ports:
      - 0.0.0.0:3306:3306
  jedivin-mongodb:
    image: mongo
    ports:
      - 0.0.0.0:27017:27017
    volumes:
      - /tmp/volumns/jedivin-mongodb/data
    environment:
      - MONGO_HOST=localhost
      - MONGO_PORT=27017
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=jedivindb
  jedivin-redis:
    image: redis:6.2.6
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:6379:6379
  kafka:
    image: confluentinc/cp-kafka:5.5.7
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.7
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000